Test package contents before anything else.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,7 +2,6 @@ name: Tests
 
 on:
   push:
-#    branches: [master]
   pull_request:
     types: [opened, synchronize, reopened]
   release:
@@ -10,8 +9,47 @@ on:
 
 jobs:
 
+  test_package:
+    name: basic package contents
+    runs-on: ubuntu-20.04
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ ubuntu-latest ]
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Apt install required packages
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y fonts-urw-base35 || true
+          sudo apt-get install -y libfreetype6-dev || true
+          sudo apt-get install -y texlive-fonts-recommended || true
+          sudo apt-get install imagemagick || true
+          sudo apt-get install php-dev php-pear
+
+      - name: Sanity check package.xml and install ImageMagick
+        run: |
+          for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done
+
+      - name: Configure and check fonts are present
+        run: |
+          pecl install package.xml
+
+      - name: Run Imagick tests
+        run: |
+          find / -name run-tests.php
+          export TEST_PHP_EXECUTABLE=`which php`
+          php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./*.phpt --show-diff
+          php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt --show-diff
+          for i in `ls tests/*.diff 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
+          php ./util/check_version.php
+
   test_basic:
     name: basic PHP ${{ matrix.php }} - I ${{ matrix.imagemagick }}
+    needs: test_package
     runs-on: ubuntu-20.04
     strategy:
       fail-fast: false
@@ -24,12 +62,6 @@ jobs:
             git7,
             git6
         ]
-#        exclude:
-#          - php: 5.4
-#            imagemagick: 6.8.7-0
-#        allow_failures:
-#         - imagemagick: git7
-#          - imagemagick: git6
 
     steps:
       - name: Checkout code
