Add basic test for 2 versions, to avoid triggering 120 builds when a typo will cause all of them to fail.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,7 +9,72 @@ on:
     types: [created]
 
 jobs:
-  test:
+
+  test_basic:
+    name: basic PHP ${{ matrix.php }} - I ${{ matrix.imagemagick }}
+    runs-on: ubuntu-20.04
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ ubuntu-latest ]
+        php: [ 5.4 ]
+        imagemagick: [
+            7.0.10-27
+            6.9.2-0
+        ]
+#        exclude:
+#          - php: 5.4
+#            imagemagick: 6.8.7-0
+#        allow_failures:
+#         - imagemagick: git7
+#          - imagemagick: git6
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ matrix.php }}
+
+      - name: Apt get commands
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y fonts-urw-base35 || true
+          sudo apt-get install -y libfreetype6-dev || true
+          sudo apt-get install -y texlive-fonts-recommended || true
+
+      - name: Prepare dependencies
+        run: |
+          for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done
+          bash ./imagemagick_dependency.sh " ${{ matrix.imagemagick }}"
+
+      - name: Setup
+        run: |
+          export NO_INTERACTION=1
+          export REPORT_EXIT_STATUS=1
+          export SKIP_SLOW_TESTS=1
+          export PHP_IMAGICK_VERSION=$(php -r '$sxe = simplexml_load_file ("package.xml"); echo (string) $sxe->version->release;')
+          export CFLAGS=$(php util/calculate_cflags.php "${{ matrix.php }}" "${{ matrix.imagemagick }}")
+          echo "CFLAGS are ${CFLAGS}"
+          phpize
+          ./configure --with-imagick="${HOME}/im/imagemagick-${{ matrix.imagemagick }}"
+          sudo make install
+          php -d extension=imagick.so util/check_fonts.php
+
+      - name: Run tests
+        run: |
+          export TEST_PHP_EXECUTABLE=`which php`
+          php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./*.phpt --show-diff
+          php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt --show-diff
+          for i in `ls tests/*.diff 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
+          php ./util/check_version.php
+
+
+  test_all:
+    name: Full PHP ${{ matrix.php }} - I ${{ matrix.imagemagick }}
+    needs: test_basic
     runs-on: ubuntu-16.04
     strategy:
       fail-fast: false
@@ -20,11 +85,11 @@ jobs:
           7.0.10-27,
           7.0.8-4,
           7.0.1-0,
-          git7,
+          # git7, doesn't seem to work currently
           6.9.2-0,
           6.8.7-0,
           6.7.8-0,
-          git6
+          # git6, doesn't seem to work currently
         ]
         exclude:
           - php: 5.4
@@ -32,8 +97,6 @@ jobs:
         allow_failures:
           - imagemagick: git7
           - imagemagick: git6
-
-    name: PHP ${{ matrix.php }} - I ${{ matrix.imagemagick }}
 
     steps:
       - name: Checkout code
